### ISSUE TITLE
App using this package fails to compile

### ISSUE THREAD

**Issue by andviane** [RSG-Group/rsg-group.github.io#2]
The app using this package works with "npm start" but the attempt to produce the production build ("npm run build") fails with the following error messages:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	/home/sv/catkin_ws/build/npm/node_modules/line-intersection/index.js:1 

Read more here: http://bit.ly/2tRViJ9
```
As a work around, I have integrated index.js in the application code directly. The provided URL should contain enough information to explain the problem.

**Comment by radi-cho** [comment]
Hello @andviane and thanks for reporting this problem.
The `line-intersection` package was moved to https://github.com/radi-cho/line-intersection but I've opened issue there as well. Check it out [here](https://github.com/radi-cho/line-intersection/issues/1) and please provide more detailed information about your environment:

- OS
- Node version
- `react-scripts` version
- `line-intersection` version
